### ISSUE TITLE
Add a support of cyrillic

### ISSUE THREAD

**Issue by Promezhson** [saluk/PyWright-godot#35]
I really want to make a russian translation for my favorite fan cases on PyWright, but my lack of programming skills are making it very troublesome. I would really appreciate it if the people who can would add support of cyrillic symbols.

**Comment by saluk** [comment]
Thanks for the interest! It will support any translation, you will just need to use a font that can support your language, and set the font variables to use that font. I'll include instructions in the guide I'm writing, and will include a couple font files that can be used.

**Comment by saluk** [comment]
Here is a quick example script, if you put roboto-regular.ttf in the fonts directory
```
set _font_tb roboto-regular.ttf
"Лорем ипсум долор сит амет, аццумсан иудицабит инструцтиор те пер."
"Ат ест виде вери. Вис деленити луцилиус сингулис ан, порро оцурререт"
"адолесценс ан дуо. Хас яуод тинцидунт ад, но еам дицат пауло, ет мел"
"перципит фацилиси. Не дуо партем глориатур. Цу вереар персеяуерис"
"цум, нец ин ерудити граецис аппеллантур, ет фалли еяуидем дебитис цум."
"Нулла еуисмод цу про, инцоррупте диссентиет ет иус, прима интегре"
"импедит ан про. Усу игнота цоммуне партиендо но, граецис сусципиантур"
"хас еа, еу оцурререт аццоммодаре хис. Елитр цомплецтитур ех нам, те"
"сит суммо ратионибус."
```
